# Generated by Django 3.2.1 on 2023-07-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=100)),
                ('num_sim', models.CharField(max_length=8, unique=True)),
                ('nro_medidor', models.CharField(max_length=10, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('clave_user', models.CharField(max_length=5)),
                ('token_activo', models.TextField()),
                ('token_nuevo', models.TextField()),
            ],
        ),
    ]
