# Generated by Django 3.2.1 on 2023-07-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_medidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidor',
            name='clave_user',
        ),
        migrations.AlterField(
            model_name='medidor',
            name='num_sim',
            field=models.IntegerField(max_length=8, unique=True),
        ),
    ]
