# Generated by Django 3.2.1 on 2023-08-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20230723_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidor',
            old_name='estado',
            new_name='estado_med',
        ),
    ]
