# Generated by Django 3.2.1 on 2023-08-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_rename_estado_medidor_estado_med'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medidor',
            old_name='estado_med',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='medidor',
            old_name='nro_medidor',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='medidor',
            old_name='num_sim',
            new_name='sim',
        ),
        migrations.AlterField(
            model_name='medidor',
            name='token_activo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='token_nuevo',
            field=models.TextField(null=True),
        ),
    ]
