# Generated by Django 3.2.1 on 2023-08-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20230801_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.medidor')),
            ],
        ),
    ]
