# Generated by Django 3.2.1 on 2023-08-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_historialconsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidor',
            name='sim',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='operador',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('OPE', 'Operador')], default='OPE', max_length=3),
        ),
    ]
