# Generated by Django 3.2.1 on 2023-08-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20230822_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialconsumo',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_consumo', to='administracion.medidor'),
        ),
    ]
